version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tricol-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_tricol_supplier_chain_security
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tricol-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: tricol-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    ports:
      - "8180:8080"
    depends_on:
      - mysql
    command: start-dev
    networks:
      - tricol-network

volumes:
  mysql_data:

networks:
  tricol-network:
    driver: bridge
